# Generated by Django 6.1.1 on 2026-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='dealer',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dealer',
            name='long',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dealer',
            name='short_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='car_make',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='car_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='review',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
